const ERROR_STATUS = {
  // Auth (401)
  AUTH_INVALID_CREDENTIALS: 401,
  AUTH_TOKEN_EXPIRED: 401,
  AUTH_UNAUTHORIZED: 401,
  AUTH_INVALID_RESET_TOKEN: 400,

  // General
  VALIDATION_ERROR: 400,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
  NO_IMAGE_PROVIDED: 400,
  IMAGE_UPLOAD_FAILED: 400,

  // User
  USER_NOT_FOUND: 404,

  // Product
  PRODUCT_SKU_ALREADY_EXISTS: 409,
  PRODUCT_NOT_FOUND: 404,
  PRODUCT_INSUFFICIENT_STOCK: 400,
  PRODUCT_UPDATE_FAILED: 500,
  PRODUCT_DELETE_FAILED: 500,

  // Category
  CATEGORY_ALREADY_EXISTS: 409,
  CATEGORY_NOT_FOUND: 404,
  CATEGORY_UPDATE_FAILED: 500,

  // Supplier
  SUPPLIER_NOT_FOUND: 404,

  // Customer
  CUSTOMER_NOT_FOUND: 404,

  // Transaction
  TRANSACTION_NOT_FOUND: 404,
  TRANSACTION_ALREADY_CANCELLED: 400,

  // Purchase
  PURCHASE_NOT_FOUND: 404,
  PURCHASE_ALREADY_PAID: 400,

  // Debt
  DEBT_ALREADY_PAID: 400,

  // Daily Report
  REPORT_NOT_FOUND: 404,
  REPORT_ALREADY_CLOSED: 400,
};

module.exports = ERROR_STATUS;
