CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  phone VARCHAR(20) DEFAULT NULL,
  store_name VARCHAR(150) DEFAULT NULL,
  address TEXT DEFAULT NULL,
  avatar_url VARCHAR(255) DEFAULT NULL,
  role ENUM('owner', 'cashier') NOT NULL DEFAULT 'cashier',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);